### ISSUE TITLE
Partial reads are not handled correctly

### ISSUE THREAD

**Issue by joao-r-reis** [datastax/go-cassandra-native-protocol#39]
Currently the library is using [Read()](https://pkg.go.dev/io#Reader) which is not guaranteed to read exactly `n` bytes but the library is assuming that it always reads the number of bytes that it requests.

Because of this we are running into errors like:

```
cannot decode frame body: cannot decode body message: cannot read RESULT Rows data row 2 col 8: not enough bytes to read [bytes] content
```

This should be easily fixed by using [io.ReadFull](https://pkg.go.dev/io#ReadFull)

┆Issue is synchronized with this [Jira Task](https://datastax.jira.com/browse/ZDM-249) by [Unito](https://www.unito.io)
┆priority: Major

**Comment by joao-r-reis** [comment]
@adutra in the process of looking at the `primitive` package to see where we are using `Read()` I saw that we are using `io.ReadAll()` in the `ReadUnsignedVint()` function (I believe this is used for the duration type). Shouldn't we limit the data that we read from the `Reader` to just what we need? The way this primitive function is being used by the duration codec makes it so that we can safely use `ReadAll()` but if a user tries to use this primitive directly or if this primitive is reused for something else, it could be an issue.

**Comment by adutra** [comment]
> @adutra in the process of looking at the `primitive` package to see where we are using `Read()` I saw that we are using `io.ReadAll()` in the `ReadUnsignedVint()` function (I believe this is used for the duration type). Shouldn't we limit the data that we read from the `Reader` to just what we need? The way this primitive function is being used by the duration codec makes it so that we can safely use `ReadAll()` but if a user tries to use this primitive directly or if this primitive is reused for something else, it could be an issue.

Hi @joao-r-reis you are absolutely right. I opened a PR #41 for that, this should complete your PR #40  to use io.ReadFull across the board. Btw I will review #40 now.
