### ISSUE TITLE
Relax codec checks to support client requests with empty query string

### ISSUE THREAD

**Issue by alicel** [datastax/go-cassandra-native-protocol#44]
The codec currently rejects client requests whose query string is empty, throwing an error that causes the decoding operation to fail. This has not been an issue so far, as CQL queries always contain a non-empty query string. This also works for Graph when sending Gremlin requests using the String APIs.

However, this is an issue when using the Gremlin Fluent APIs for Graph, as the GraphBinary subprotocol always leaves the query string empty.

To allow Fluent API Gremlin requests to be handled without errors, we need to remove the empty query string check. In general, this will give clients the ability to submit requests with empty strings when appropriate for the subprotocol that they are using.

**Comment by adutra** [comment]
@alicel isn't this fixed already?

**Comment by alicel** [comment]
Yes, this issue can be closed.
